<div>
<img src=https://www.institutedata.com/wp-content/uploads/2019/10/iod_h_tp_primary_c.svg width="300">
</div>

# Lab 3.1.4 
# *Python with MongoDB*

## Introduction to PyMongo

In [1]:
#from IPython.core.display import display, HTML
import pymongo
from pymongo import MongoClient

print ('Mongo version ' + pymongo.__version__)

Mongo version 3.12.0


Start the mongod server (if it isn't lready running) by executing  
`mongod`  
at the command prompt. 

In [2]:
client = pymongo.MongoClient("mongodb+srv://draj:Newtomongo@cluster0.ka1guql.mongodb.net/?retryWrites=true&w=majority",
                             tlsCAFile=r'C:\Users\Sanjeshni\anaconda3\lib\site-packages\certifi\cacert.pem')
#db = client.test

In [3]:
client

MongoClient(host=['ac-4orvc80-shard-00-00.ka1guql.mongodb.net:27017', 'ac-4orvc80-shard-00-02.ka1guql.mongodb.net:27017', 'ac-4orvc80-shard-00-01.ka1guql.mongodb.net:27017'], document_class=dict, tz_aware=False, connect=True, retrywrites=True, w='majority', authsource='admin', replicaset='atlas-10ukvm-shard-0', ssl=True, ssl_ca_certs='C:\\Users\\Sanjeshni\\anaconda3\\lib\\site-packages\\certifi\\cacert.pem')

Create a new database:

In [4]:
mydb = client["collection"]

Confirm that the database exists ... 

- list all databases in your system:

In [5]:
print(client.list_database_names())

['collection', 'divdb', 'admin', 'local']


- check for the database by name:

In [6]:
dblist = client.list_database_names()
if "collection" in dblist:  
    print("The database exists.")

The database exists.


The new database was not found because mongodb is lazy: the db won't get created until data has been written to it!

Create a collection called "customers" (with object name `mycol`):

In [7]:
mycol = mydb["customers"]

Create a document (i.e. a dictionary) with two name:value items 
("name" = "John", and "address" = "Highway 37") and insert 
it into the "customers" collection: 

In [8]:
customers = { "name": "John", "address": "Highway 37" }
x = mycol.insert_one(customers)


Now test for the existence of the database:

List all collections in the database:

In [9]:
print(client.list_database_names())

['collection', 'divdb', 'admin', 'local']


Insert another record in the "customers" collection 
("name" = "Peter", "address" = "Lowstreet 27") 
and return the value of the _id field:

In [10]:
mydict = { "name": "Peter", "address": "Lowstreet 27" }
x = mycol.insert_one(mydict)
print(x.inserted_id)


63e1fb25361b7b528b0972a6


Given the list of dicts below, insert multiple documents into 
the collection using the insert_many() method:

In [11]:
mylist = [
  { "name": "Amy", "address": "Apple st 652"},
  { "name": "Hannah", "address": "Mountain 21"},
  { "name": "Michael", "address": "Valley 345"},
  { "name": "Sandy", "address": "Ocean blvd 2"},
  { "name": "Betty", "address": "Green Grass 1"},
  { "name": "Richard", "address": "Sky st 331"},
  { "name": "Susan", "address": "One way 98"},
  { "name": "Vicky", "address": "Yellow Garden 2"},
  { "name": "Ben", "address": "Park Lane 38"},
  { "name": "William", "address": "Central st 954"},
  { "name": "Chuck", "address": "Main Road 989"},
  { "name": "Viola", "address": "Sideway 1633"}
]

In [12]:
x = mycol.insert_many(mylist)

Print a list of the _id values of the inserted documents:

In [13]:
print(x.inserted_ids)

[ObjectId('63e1fb26361b7b528b0972a7'), ObjectId('63e1fb26361b7b528b0972a8'), ObjectId('63e1fb26361b7b528b0972a9'), ObjectId('63e1fb26361b7b528b0972aa'), ObjectId('63e1fb26361b7b528b0972ab'), ObjectId('63e1fb26361b7b528b0972ac'), ObjectId('63e1fb26361b7b528b0972ad'), ObjectId('63e1fb26361b7b528b0972ae'), ObjectId('63e1fb26361b7b528b0972af'), ObjectId('63e1fb26361b7b528b0972b0'), ObjectId('63e1fb26361b7b528b0972b1'), ObjectId('63e1fb26361b7b528b0972b2')]


Execute the next cell to insert a list of dicts with specified `_id`s:

In [14]:
mylist = [
  { "_id": 1, "name": "John", "address": "Highway 37"},
  { "_id": 2, "name": "Peter", "address": "Lowstreet 27"},
  { "_id": 3, "name": "Amy", "address": "Apple st 652"},
  { "_id": 4, "name": "Hannah", "address": "Mountain 21"},
  { "_id": 5, "name": "Michael", "address": "Valley 345"},
  { "_id": 6, "name": "Sandy", "address": "Ocean blvd 2"},
  { "_id": 7, "name": "Betty", "address": "Green Grass 1"},
  { "_id": 8, "name": "Richard", "address": "Sky st 331"},
  { "_id": 9, "name": "Susan", "address": "One way 98"},
  { "_id": 10, "name": "Vicky", "address": "Yellow Garden 2"},
  { "_id": 11, "name": "Ben", "address": "Park Lane 38"},
  { "_id": 12, "name": "William", "address": "Central st 954"},
  { "_id": 13, "name": "Chuck", "address": "Main Road 989"},
  { "_id": 14, "name": "Viola", "address": "Sideway 1633"}
]
x = mycol.insert_many(mylist)
print(x.inserted_ids)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]


Now try inserting a new dict with an existing `_id`:

In [15]:
x = mycol.insert_one({ "_id": 14, "name": "Manuel", "address": "Barcelona"})

DuplicateKeyError: E11000 duplicate key error collection: collection.customers index: _id_ dup key: { _id: 14 }, full error: {'index': 0, 'code': 11000, 'keyPattern': {'_id': 1}, 'keyValue': {'_id': 14}, 'errmsg': 'E11000 duplicate key error collection: collection.customers index: _id_ dup key: { _id: 14 }'}

So, if we want to manage `_id`s in code, we need to be careful!

This returns the first document in the collection:

In [ ]:
x = mycol.find_one()
print(x)

Do the same for the document containing "name" = "Hannah":

In [16]:
x = mycol.find_one({"name":"Hannah"})
print(x)

{'_id': ObjectId('63e1fb26361b7b528b0972a8'), 'name': 'Hannah', 'address': 'Mountain 21'}


This returns (and prints) all documents in the collection:

In [17]:
for x in mycol.find():
  print(x)

{'_id': ObjectId('63d8e5a6259b994af5842ecb'), 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': ObjectId('63d8e5b0259b994af5842ecc'), 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': ObjectId('63d8e6ec259b994af5842ece'), 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': ObjectId('63d8ec0f259b994af5842ed2'), 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': ObjectId('63da193d6cced3bab3be3006'), 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': ObjectId('63da197e6cced3bab3be3007'), 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': ObjectId('63da19fc6cced3bab3be3008'), 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': ObjectId('63da1b396cced3bab3be3009'), 'name': 'John', 'address': 'Highway 37'}
{'_id': ObjectId('63da1b856cced3bab3be300a'), 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': ObjectId('63da1bdf6cced3bab3be300b'), 'name': 'Amy', 'address': 'Apple st 652'}
{'_id': ObjectId('63da1bdf6cced3bab3be300d'), 'name': 'Michael', 'address': 'Canyon 123'}
{'_id': ObjectI

This returns only the name and address fields:

In [18]:
for x in mycol.find({},{ "_id": 0, "name": 1, "address": 1 }):
  print(x)

{'name': 'Peter', 'address': 'Lowstreet 27'}
{'name': 'Peter', 'address': 'Lowstreet 27'}
{'name': 'Peter', 'address': 'Lowstreet 27'}
{'name': 'Peter', 'address': 'Lowstreet 27'}
{'name': 'Peter', 'address': 'Lowstreet 27'}
{'name': 'Peter', 'address': 'Lowstreet 27'}
{'name': 'Peter', 'address': 'Lowstreet 27'}
{'name': 'John', 'address': 'Highway 37'}
{'name': 'Peter', 'address': 'Lowstreet 27'}
{'name': 'Amy', 'address': 'Apple st 652'}
{'name': 'Michael', 'address': 'Canyon 123'}
{'name': 'Sandy', 'address': 'Ocean blvd 2'}
{'name': 'Betty', 'address': 'Green Grass 1'}
{'name': 'Richard', 'address': 'Sky st 331'}
{'name': 'Susan', 'address': 'One way 98'}
{'name': 'Vicky', 'address': 'Yellow Garden 2'}
{'name': 'Ben', 'address': 'Park Lane 38'}
{'name': 'William', 'address': 'Central st 954'}
{'name': 'Chuck', 'address': 'Main Road 989'}
{'name': 'Viola', 'address': 'Sideway 1633'}
{'name': 'John', 'address': 'Highway 37'}
{'name': 'Peter', 'address': 'Lowstreet 27'}
{'name': 'Amy

Print only the `_id` and name fields:

In [19]:
for x in mycol.find({},{"_id": 1, "name":1}):
    print(x)

{'_id': ObjectId('63d8e5a6259b994af5842ecb'), 'name': 'Peter'}
{'_id': ObjectId('63d8e5b0259b994af5842ecc'), 'name': 'Peter'}
{'_id': ObjectId('63d8e6ec259b994af5842ece'), 'name': 'Peter'}
{'_id': ObjectId('63d8ec0f259b994af5842ed2'), 'name': 'Peter'}
{'_id': ObjectId('63da193d6cced3bab3be3006'), 'name': 'Peter'}
{'_id': ObjectId('63da197e6cced3bab3be3007'), 'name': 'Peter'}
{'_id': ObjectId('63da19fc6cced3bab3be3008'), 'name': 'Peter'}
{'_id': ObjectId('63da1b396cced3bab3be3009'), 'name': 'John'}
{'_id': ObjectId('63da1b856cced3bab3be300a'), 'name': 'Peter'}
{'_id': ObjectId('63da1bdf6cced3bab3be300b'), 'name': 'Amy'}
{'_id': ObjectId('63da1bdf6cced3bab3be300d'), 'name': 'Michael'}
{'_id': ObjectId('63da1bdf6cced3bab3be300e'), 'name': 'Sandy'}
{'_id': ObjectId('63da1bdf6cced3bab3be300f'), 'name': 'Betty'}
{'_id': ObjectId('63da1bdf6cced3bab3be3010'), 'name': 'Richard'}
{'_id': ObjectId('63da1bdf6cced3bab3be3011'), 'name': 'Susan'}
{'_id': ObjectId('63da1bdf6cced3bab3be3012'), 'name': 

So, we must explicitly use `"_id": 0` to exclude it, but for other fields we simply omit them from the dict argument.

To include field conditionals in a query, we use `$` operators. This finds addresses starting with "S" or greater:

In [20]:
myquery = { "address": { "$gt": "S" } }
mydoc = mycol.find(myquery)
for x in mydoc:
  print(x)

{'_id': ObjectId('63da1bdf6cced3bab3be3010'), 'name': 'Richard', 'address': 'Sky st 331'}
{'_id': ObjectId('63da1bdf6cced3bab3be3012'), 'name': 'Vicky', 'address': 'Yellow Garden 2'}
{'_id': ObjectId('63da1bdf6cced3bab3be3016'), 'name': 'Viola', 'address': 'Sideway 1633'}
{'_id': ObjectId('63e1fb26361b7b528b0972a9'), 'name': 'Michael', 'address': 'Valley 345'}
{'_id': ObjectId('63e1fb26361b7b528b0972ac'), 'name': 'Richard', 'address': 'Sky st 331'}
{'_id': ObjectId('63e1fb26361b7b528b0972ae'), 'name': 'Vicky', 'address': 'Yellow Garden 2'}
{'_id': ObjectId('63e1fb26361b7b528b0972b2'), 'name': 'Viola', 'address': 'Sideway 1633'}
{'_id': 5, 'name': 'Michael', 'address': 'Valley 345'}
{'_id': 8, 'name': 'Richard', 'address': 'Sky st 331'}
{'_id': 10, 'name': 'Vicky', 'address': 'Yellow Garden 2'}
{'_id': 14, 'name': 'Viola', 'address': 'Sideway 1633'}


Here are some more comparison operators:

            $gt, $gte, $eq, $in, $nin, $exists, $and, $or, $not
            
Experiment with these until you understand how to use them.

Now find all docs with an address that begins with "S":  
(HINT: The value for "address" in the argument should be the regex-based dict { "$regex": "^S" }.)

In [21]:
#ANSWER:
myquery = { "address": { "$regex": "^S" } }
mydoc = mycol.find(myquery)
for x in mydoc:
  print(x)

{'_id': ObjectId('63da1bdf6cced3bab3be3010'), 'name': 'Richard', 'address': 'Sky st 331'}
{'_id': ObjectId('63da1bdf6cced3bab3be3016'), 'name': 'Viola', 'address': 'Sideway 1633'}
{'_id': ObjectId('63e1fb26361b7b528b0972ac'), 'name': 'Richard', 'address': 'Sky st 331'}
{'_id': ObjectId('63e1fb26361b7b528b0972b2'), 'name': 'Viola', 'address': 'Sideway 1633'}
{'_id': 8, 'name': 'Richard', 'address': 'Sky st 331'}
{'_id': 14, 'name': 'Viola', 'address': 'Sideway 1633'}


Sorting can be applied by invoking the Sort() method after the Find() method. Sort the collection by the name field:

In [22]:
#ANSWER:
mydoc = mycol.find().sort("name")
for x in mydoc:
  print(x)

{'_id': ObjectId('63da1bdf6cced3bab3be300b'), 'name': 'Amy', 'address': 'Apple st 652'}
{'_id': ObjectId('63e1fb26361b7b528b0972a7'), 'name': 'Amy', 'address': 'Apple st 652'}
{'_id': 3, 'name': 'Amy', 'address': 'Apple st 652'}
{'_id': ObjectId('63da1bdf6cced3bab3be3013'), 'name': 'Ben', 'address': 'Park Lane 38'}
{'_id': ObjectId('63e1fb26361b7b528b0972af'), 'name': 'Ben', 'address': 'Park Lane 38'}
{'_id': 11, 'name': 'Ben', 'address': 'Park Lane 38'}
{'_id': ObjectId('63da1bdf6cced3bab3be300f'), 'name': 'Betty', 'address': 'Green Grass 1'}
{'_id': ObjectId('63e1fb26361b7b528b0972ab'), 'name': 'Betty', 'address': 'Green Grass 1'}
{'_id': 7, 'name': 'Betty', 'address': 'Green Grass 1'}
{'_id': ObjectId('63da1bdf6cced3bab3be3015'), 'name': 'Chuck', 'address': 'Main Road 989'}
{'_id': ObjectId('63e1fb26361b7b528b0972b1'), 'name': 'Chuck', 'address': 'Main Road 989'}
{'_id': 13, 'name': 'Chuck', 'address': 'Main Road 989'}
{'_id': ObjectId('63e1fb26361b7b528b0972a8'), 'name': 'Hannah', 

Now sort in reverse order (HINT: The Sort() method takes an optional second parameter.)

In [23]:
mydoc = mycol.find().sort([("name", pymongo.DESCENDING)])
for x in mydoc:
  print(x)

{'_id': ObjectId('63da1bdf6cced3bab3be3014'), 'name': 'William', 'address': 'Central st 954'}
{'_id': ObjectId('63e1fb26361b7b528b0972b0'), 'name': 'William', 'address': 'Central st 954'}
{'_id': 12, 'name': 'William', 'address': 'Central st 954'}
{'_id': ObjectId('63da1bdf6cced3bab3be3016'), 'name': 'Viola', 'address': 'Sideway 1633'}
{'_id': ObjectId('63e1fb26361b7b528b0972b2'), 'name': 'Viola', 'address': 'Sideway 1633'}
{'_id': 14, 'name': 'Viola', 'address': 'Sideway 1633'}
{'_id': ObjectId('63da1bdf6cced3bab3be3012'), 'name': 'Vicky', 'address': 'Yellow Garden 2'}
{'_id': ObjectId('63e1fb26361b7b528b0972ae'), 'name': 'Vicky', 'address': 'Yellow Garden 2'}
{'_id': 10, 'name': 'Vicky', 'address': 'Yellow Garden 2'}
{'_id': ObjectId('63da1bdf6cced3bab3be3011'), 'name': 'Susan', 'address': 'One way 98'}
{'_id': ObjectId('63e1fb26361b7b528b0972ad'), 'name': 'Susan', 'address': 'One way 98'}
{'_id': 9, 'name': 'Susan', 'address': 'One way 98'}
{'_id': ObjectId('63da1bdf6cced3bab3be300e

A single record can be deleted by specifying some criterion:

In [24]:
mycol.delete_one({ "address": "Mountain 21" })

Now delete all docs with the 2-digit `Id` values:

In [25]:
mycol.delete_many({ "_id": {"$lt": 15} })
for x in mycol.find():
  print(x)

{'_id': ObjectId('63d8e5a6259b994af5842ecb'), 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': ObjectId('63d8e5b0259b994af5842ecc'), 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': ObjectId('63d8e6ec259b994af5842ece'), 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': ObjectId('63d8ec0f259b994af5842ed2'), 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': ObjectId('63da193d6cced3bab3be3006'), 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': ObjectId('63da197e6cced3bab3be3007'), 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': ObjectId('63da19fc6cced3bab3be3008'), 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': ObjectId('63da1b396cced3bab3be3009'), 'name': 'John', 'address': 'Highway 37'}
{'_id': ObjectId('63da1b856cced3bab3be300a'), 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': ObjectId('63da1bdf6cced3bab3be300b'), 'name': 'Amy', 'address': 'Apple st 652'}
{'_id': ObjectId('63da1bdf6cced3bab3be300d'), 'name': 'Michael', 'address': 'Canyon 123'}
{'_id': ObjectI

This would delete all docs:
`x = mycol.delete_many({})`

This would remove the collection:
`mycol.drop()`

Change the first instance of "address" == "Valley 345" to "Canyon 123" using update_one().  
(HINT: The 1st paramater of update_one() is the criterion (query); the 2nd is dict specifying the field to change and its new value.) 

In [26]:
#ANSWER:
myquery = { "address": "Valley 345" }
newvalues = { "$set": { "address": "Canyon 123" } }
mycol.update_one(myquery, newvalues)
for x in mycol.find():
  print(x)

{'_id': ObjectId('63d8e5a6259b994af5842ecb'), 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': ObjectId('63d8e5b0259b994af5842ecc'), 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': ObjectId('63d8e6ec259b994af5842ece'), 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': ObjectId('63d8ec0f259b994af5842ed2'), 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': ObjectId('63da193d6cced3bab3be3006'), 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': ObjectId('63da197e6cced3bab3be3007'), 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': ObjectId('63da19fc6cced3bab3be3008'), 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': ObjectId('63da1b396cced3bab3be3009'), 'name': 'John', 'address': 'Highway 37'}
{'_id': ObjectId('63da1b856cced3bab3be300a'), 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': ObjectId('63da1bdf6cced3bab3be300b'), 'name': 'Amy', 'address': 'Apple st 652'}
{'_id': ObjectId('63da1bdf6cced3bab3be300d'), 'name': 'Michael', 'address': 'Canyon 123'}
{'_id': ObjectI

The limit() method can be applied after the find() method to limit the number of docs returned. Show the first 5 docs:

In [27]:
#ANSWER:
myresult = mycol.find().limit(5)
for x in myresult:
  print(x)

{'_id': ObjectId('63d8e5a6259b994af5842ecb'), 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': ObjectId('63d8e5b0259b994af5842ecc'), 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': ObjectId('63d8e6ec259b994af5842ece'), 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': ObjectId('63d8ec0f259b994af5842ed2'), 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': ObjectId('63da193d6cced3bab3be3006'), 'name': 'Peter', 'address': 'Lowstreet 27'}


## PyMongo for Data Science

MongoDB has many more features of interest to developers, but the main focus of a data scientist will be wrangling and munging the data. It may or may not be desirable to do all the data munging in Pandas; for a large, distributed database, it may be imperative to perform aggregation in MongoDB. 

In [28]:
#Ref:  https://rsandstroem.github.io/MongoDBDemo.html

#import os
#import pandas as pd
#import numpy as np

This code creates a database named "test" and populates it from a JSON file using the mongoimport program (executed in the operating systems itself, rather than in Python):

In [29]:
import os
import pandas as pd
import numpy as np
from IPython.core.display import display, HTML
import pymongo
import json
from pymongo import MongoClient
print ('Mongo version ' + pymongo.__version__)
client = pymongo.MongoClient("mongodb+srv://draj:Newtomongo@cluster0.ka1guql.mongodb.net/?retryWrites=true&w=majority",
                             tlsCAFile=r'C:\Users\Sanjeshni\anaconda3\lib\site-packages\certifi\cacert.pem')
db = client.test
collection = db.people

Mongo version 3.12.0


In [30]:
os.chdir('C:\\Users\\Sanjeshni\\Documents\\DIV_IOD\\Module 3')

In [31]:
pwd()

'C:\\Users\\Sanjeshni\\Documents\\DIV_IOD\\Module 3'

In [32]:
# if this does not return 0, execute mongoimport from a commmand window instead:

os.system('mongoimport -d test -c people dummyData.json')

1

In [160]:
os.chdir("..")

In [161]:
pwd()

'C:\\Users\\Sanjeshni\\Documents\\DIV_IOD'

In [162]:
db = client.test
collection = db.people
cursor = collection.find().sort('Age',pymongo.ASCENDING).limit(3)
for doc in cursor:
    print (doc)

Here is a small demonstration of the MongoDB aggregation framework. We want to create a table of the number of persons in each country and their average age. To do it we group by country. We extract the results from MongoDB aggregation into a pandas dataframe, and use the country as index.

In [98]:
pipeline = [
        {"$group": {"_id":"$Country",
             "AvgAge":{"$avg":"$Age"},
             "Count":{"$sum":1},
        }},
        {"$sort":{"Count":-1,"AvgAge":1}}
]
aggResult = collection.aggregate(pipeline) # returns a cursor

df1 = pd.DataFrame(list(aggResult)) # use list to turn the cursor to an array of documents
df1 = df1.set_index("_id")
df1.head()

KeyError: "None of ['_id'] are in the columns"

For simple cases one can either use a cursor through find("search term") or use the "$match" operator in the aggregation framework, like this:

In [ ]:
pipeline = [
        {"$match": {"Country":"China"}},
]
aggResult = collection.aggregate(pipeline)
df2 = pd.DataFrame(list(aggResult))
df2.head()

Now we can apply all the power of Python libraries to analyse and visualise the data. Here, we will use the folium package to plot markers for the locations of the people we just found in China (click on a marker to see their data):

In [ ]:
# Un-comment and execute to install folium pkg (1st time only):
# import sys
# !{sys.executable} -m pip install folium

In [ ]:
import folium
print ('Folium version ' + folium.__version__)

world_map = folium.Map(location = [35, 100], zoom_start = 4)
for i in range(len(df2)):
    location = [float(loc) for loc in df2.Location[i].split(',')]
    folium.Marker(location = location, popup = df2.Name[i] + ', age:' + str(df2.Age[i])).add_to(world_map)
    
world_map

## HOMEWORK:


1. Read up on how to perform aggregation in mongoDB. Insert a duplicate record into the collection:
        mydict = { "name": "John", "address": "Highway 37" }
   Now write a command to find docs with a duplicate "name" field (using aggregation) and remove them.  
   Print the collection.

2. Read up on how to apply indexes in mongoDB. Create an index on the "name" and "address" fields in this collection.
   Print the indexes for the collection.



> 
>
>






---



---



> > > > > > > > > © 2022 Institute of Data


---



---



